name = "powermenu"
name_pretty = "Power Menu"
icon = "applications-other"

[[entries]]
icon = "system-shutdown"
text = "Shutdown"
actions = { "shutdown" = "systemctl poweroff" }

[[entries]]
icon = "system-reboot"
text = "Reboot"
actions = { "reboot" = "systemctl reboot" }

[[entries]]
icon = "system-hibernate"
text = "Hibernate"
actions = { "hibernate" = "systemctl hibernate" }

[[entries]]
icon = "system-suspend"
text = "Suspend"
actions = { "suspend" = "systemctl suspend" }

[[entries]]
icon = "system-logout"
text = "Logout"
actions = { "logout" = "loginctl terminate-session ${XDG_SESSION_ID-}" }
