name = "powermenu"
name_pretty = "Power Menu"
icon = "applications-other"
global_search = true

[[entries]]
actions = { "shutdown" = "systemctl poweroff" }
icon = "system-shutdown"
text = "Shutdown"

[[entries]]
actions = { "reboot" = "systemctl reboot" }
icon = "system-reboot"
text = "Reboot"

[[entries]]
actions = { "hibernate" = "systemctl hibernate" }
icon = "system-hibernate"
text = "Hibernate"

[[entries]]
actions = { "suspend" = "systemctl suspend" }
icon = "system-suspend"
text = "Suspend"

[[entries]]
actions = { "logout" = "loginctl terminate-session ${XDG_SESSION_ID-}" }
icon = "system-logout"
text = "Logout"
